using ClosedXML.Excel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ResolveHub.Api.DTOs.Tickets;
using ResolveHub.Api.Services.Interfaces;

namespace ResolveHub.Api.Services.Implementations;

public sealed class AdminTicketReportService : IAdminTicketReportService
{
    private static readonly string[] Headers =
        ["Ticket Number", "Title", "Requester", "Category", "Priority", "Status", "Assigned Agent", "Created"];
    private static readonly string[] StatusBreakdownOrder =
        ["Open", "Assigned", "In Progress", "Pending", "Resolved", "Closed", "Cancelled", "Duplicate"];
    private static readonly string[] PriorityBreakdownOrder = ["Critical", "High", "Medium", "Low"];

    public byte[] CreatePdf(AdminTicketReportDto report, string generatedBy,
        DateTimeOffset generatedAt, string? timeZoneId)
    {
        var (timeZone, _) = ResolveTimeZone(timeZoneId);
        var localGeneratedAt = ToLocalTime(generatedAt.UtcDateTime, timeZone);
        return
        Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(24);
            page.DefaultTextStyle(style => style.FontSize(8).FontColor(Colors.Grey.Darken3));
            page.Header().Column(column =>
            {
                column.Item().Text("ResolveHub").FontSize(18).Bold().FontColor("1769C2");
                column.Item().Text("Ticket Report").FontSize(14).SemiBold();
                column.Item().PaddingTop(5).Text($"Generated: {localGeneratedAt:MMM d, yyyy h:mm tt}  |  Generated By: {generatedBy}")
                    .FontColor(Colors.Grey.Darken1);
            });
            page.Content().PaddingVertical(12).Column(column =>
            {
                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1.1f); columns.RelativeColumn(2.4f);
                        columns.RelativeColumn(1.5f); columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1); columns.RelativeColumn(1.1f);
                        columns.RelativeColumn(1.5f); columns.RelativeColumn(1.35f);
                    });
                    table.Header(header =>
                    {
                        foreach (var title in Headers)
                            header.Cell().Background("1769C2").Padding(5).Text(title).Bold().FontColor(Colors.White);
                    });
                    foreach (var ticket in report.Tickets)
                    {
                        AddPdfCell(table, ticket.TicketReferenceNumber);
                        AddPdfCell(table, ticket.Title);
                        AddPdfCell(table, ticket.RequesterName);
                        AddPdfCell(table, ticket.CategoryName);
                        AddPdfCell(table, ticket.PriorityName);
                        AddPdfCell(table, ticket.StatusName);
                        AddPdfCell(table, ticket.AssignedAgentName ?? "Unassigned");
                        AddPdfCell(table, ToLocalTime(ticket.CreatedDate, timeZone).ToString("MMM d, yyyy h:mm tt"));
                    }
                });
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.Span("Page "); text.CurrentPageNumber(); text.Span(" of "); text.TotalPages();
            });
        })).GeneratePdf();
    }

    public byte[] CreateExcel(AdminTicketReportDto report, string generatedBy,
        DateTimeOffset generatedAt, string? timeZoneId)
    {
        var (timeZone, _) = ResolveTimeZone(timeZoneId);
        var localGeneratedAt = ToLocalTime(generatedAt.UtcDateTime, timeZone);
        using var workbook = new XLWorkbook();
        var blue = XLColor.FromHtml("#1769C2");
        var paleBlue = XLColor.FromHtml("#EAF3FD");
        var lightBorder = XLColor.FromHtml("#DCE5EE");
        var summary = workbook.AddWorksheet("Summary");
        summary.ShowGridLines = false;
        summary.Range("A1:H1").Merge().Value = "ResolveHub";
        summary.Range("A1:H1").Style.Font.SetBold().Font.SetFontSize(18).Font.SetFontColor(blue);
        summary.Range("A2:H2").Merge().Value = "Ticket Report";
        summary.Range("A2:H2").Style.Font.SetBold().Font.SetFontSize(14);
        summary.Range("A4:H4").Merge().Value = $"Generated: {localGeneratedAt:MMM d, yyyy h:mm tt}";
        summary.Range("A5:H5").Merge();
        SetSafeText(summary.Cell("A5"), $"Generated By: {generatedBy}");
        summary.Range("A4:H5").Style.Font.SetFontColor(XLColor.FromHtml("#637083")).Font.SetFontSize(10);

        summary.Range("A7:H7").Merge().Value = "REPORT CRITERIA";
        ApplySectionHeading(summary.Range("A7:H7"), blue);
        summary.Range("A8:H8").Merge();
        SetSafeText(summary.Cell("A8"), ReportCriteria(report, timeZone));
        summary.Range("A8:H8").Style.Fill.SetBackgroundColor(XLColor.FromHtml("#F7F9FC"));
        summary.Range("A8:H8").Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        summary.Range("A8:H8").Style.Border.OutsideBorderColor = lightBorder;
        summary.Range("A8:H8").Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        summary.Range("A8:H8").Style.Alignment.WrapText = true;
        summary.Row(8).Height = 28;

        summary.Range("A10:B10").Merge().Value = "TOTAL TICKETS";
        summary.Range("A11:B12").Merge();
        summary.Cell("A11").SetValue(report.Tickets.Count);
        summary.Range("A10:B12").Style.Fill.SetBackgroundColor(paleBlue);
        summary.Range("A10:B12").Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        summary.Range("A10:B12").Style.Border.OutsideBorderColor = XLColor.FromHtml("#BDD4EA");
        summary.Range("A10:B12").Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        summary.Range("A10:B12").Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        summary.Range("A10:B10").Style.Font.SetBold().Font.SetFontSize(9).Font.SetFontColor(blue);
        summary.Range("A11:B12").Style.Font.SetBold().Font.SetFontSize(22).Font.SetFontColor(blue);

        var statusCounts = report.Tickets.GroupBy(ticket => ticket.StatusName)
            .OrderBy(group => DisplayOrder(group.Key, StatusBreakdownOrder)).ThenBy(group => group.Key)
            .Select(group => (group.Key, group.Count())).ToList();
        var priorityCounts = report.Tickets.GroupBy(ticket => ticket.PriorityName)
            .OrderBy(group => DisplayOrder(group.Key, PriorityBreakdownOrder)).ThenBy(group => group.Key)
            .Select(group => (group.Key, group.Count())).ToList();
        var categoryCounts = report.Tickets.GroupBy(ticket => ticket.CategoryName)
            .OrderBy(group => group.Key).Select(group => (group.Key, group.Count())).ToList();
        WriteBreakdown(summary, 14, 1, "STATUS BREAKDOWN", statusCounts, blue, lightBorder);
        WriteBreakdown(summary, 14, 4, "PRIORITY BREAKDOWN", priorityCounts, blue, lightBorder);
        WriteBreakdown(summary, 14, 7, "CATEGORY BREAKDOWN", categoryCounts, blue, lightBorder);

        summary.Column(1).Width = 20; summary.Column(2).Width = 10;
        summary.Column(3).Width = 4; summary.Column(4).Width = 20;
        summary.Column(5).Width = 10; summary.Column(6).Width = 4;
        summary.Column(7).Width = 22; summary.Column(8).Width = 10;
        summary.PageSetup.PageOrientation = XLPageOrientation.Portrait;
        summary.PageSetup.PagesWide = 1;
        summary.PageSetup.PagesTall = 1;
        summary.PageSetup.Margins.SetTop(0.5).SetBottom(0.5).SetLeft(0.5).SetRight(0.5);

        var tickets = workbook.AddWorksheet("Tickets");
        tickets.ShowGridLines = false;
        for (var column = 0; column < Headers.Length; column++) tickets.Cell(1, column + 1).Value = Headers[column];
        var header = tickets.Range(1, 1, 1, Headers.Length);
        header.Style.Font.SetBold().Font.SetFontColor(XLColor.White);
        header.Style.Fill.SetBackgroundColor(blue);
        header.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Center);
        header.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
        header.Style.Border.BottomBorderColor = blue;
        tickets.Row(1).Height = 24;
        for (var index = 0; index < report.Tickets.Count; index++)
        {
            var ticket = report.Tickets.ElementAt(index);
            var row = index + 2;
            SetSafeText(tickets.Cell(row, 1), ticket.TicketReferenceNumber);
            SetSafeText(tickets.Cell(row, 2), ticket.Title);
            SetSafeText(tickets.Cell(row, 3), ticket.RequesterName);
            SetSafeText(tickets.Cell(row, 4), ticket.CategoryName);
            SetSafeText(tickets.Cell(row, 5), ticket.PriorityName);
            SetSafeText(tickets.Cell(row, 6), ticket.StatusName);
            SetSafeText(tickets.Cell(row, 7), ticket.AssignedAgentName ?? "Unassigned");
            tickets.Cell(row, 8).Value = ToLocalTime(ticket.CreatedDate, timeZone);
            tickets.Cell(row, 8).Style.DateFormat.Format = "mmm d, yyyy h:mm AM/PM";
            var rowRange = tickets.Range(row, 1, row, Headers.Length);
            rowRange.Style.Border.BottomBorder = XLBorderStyleValues.Hair;
            rowRange.Style.Border.BottomBorderColor = lightBorder;
            rowRange.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Top);
            if (index % 2 == 1) rowRange.Style.Fill.SetBackgroundColor(XLColor.FromHtml("#F8FAFC"));
            tickets.Row(row).Height = 30;
        }
        tickets.SheetView.FreezeRows(1);
        tickets.RangeUsed()?.SetAutoFilter();
        var widths = new[] { 18d, 42d, 24d, 20d, 14d, 18d, 24d, 23d };
        for (var index = 0; index < widths.Length; index++) tickets.Column(index + 1).Width = widths[index];
        tickets.Column(2).Style.Alignment.WrapText = true;
        tickets.PageSetup.PageOrientation = XLPageOrientation.Landscape;
        tickets.PageSetup.PagesWide = 1;
        tickets.PageSetup.PagesTall = 0;
        tickets.PageSetup.SetRowsToRepeatAtTop(1, 1);
        tickets.PageSetup.Margins.SetTop(0.5).SetBottom(0.5).SetLeft(0.35).SetRight(0.35);
        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public string CreateFileName(AdminTicketReportDto report, string extension,
        DateTimeOffset generatedAt, string? timeZoneId)
    {
        var (timeZone, _) = ResolveTimeZone(timeZoneId);
        var localGeneratedAt = ToLocalTime(generatedAt.UtcDateTime, timeZone);
        var range = report.FromUtc.HasValue && report.ToUtcExclusive.HasValue
            ? $"{ToLocalTime(report.FromUtc.Value.UtcDateTime, timeZone):yyyy-MM-dd}_to_{ToLocalTime(report.ToUtcExclusive.Value.UtcDateTime, timeZone).AddTicks(-1):yyyy-MM-dd}"
            : $"All_Dates_{localGeneratedAt:yyyy-MM-dd}";
        return $"ResolveHub_Ticket_Report_{range}.{extension}";
    }

    private static string DateRange(AdminTicketReportDto report, TimeZoneInfo timeZone) =>
        report.FromUtc.HasValue && report.ToUtcExclusive.HasValue
            ? $"{ToLocalTime(report.FromUtc.Value.UtcDateTime, timeZone):yyyy-MM-dd} to {ToLocalTime(report.ToUtcExclusive.Value.UtcDateTime, timeZone).AddTicks(-1):yyyy-MM-dd}"
            : "All Dates";

    private static void AddPdfCell(TableDescriptor table, string value) =>
        table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4).Text(value);

    private static void SetSafeText(IXLCell cell, string value)
    {
        var safeValue = value.Length > 0 && "=+-@".Contains(value[0]) ? $"'{value}" : value;
        cell.Value = safeValue;
    }

    private static string ReportCriteria(AdminTicketReportDto report, TimeZoneInfo timeZone)
    {
        var criteria = new List<string>();
        if (!string.Equals(report.Search, "All", StringComparison.OrdinalIgnoreCase))
            criteria.Add($"Search: \"{report.Search}\"");
        if (!string.Equals(report.Status, "All", StringComparison.OrdinalIgnoreCase))
            criteria.Add($"Status: {report.Status}");
        if (!string.Equals(report.Category, "All", StringComparison.OrdinalIgnoreCase))
            criteria.Add($"Category: {report.Category}");
        if (!string.Equals(report.Priority, "All", StringComparison.OrdinalIgnoreCase))
            criteria.Add($"Priority: {report.Priority}");
        var dateRange = DateRange(report, timeZone);
        if (dateRange != "All Dates") criteria.Add($"Date Range: {dateRange}");
        return criteria.Count == 0 ? "All Tickets" : string.Join("  •  ", criteria);
    }

    private static int DisplayOrder(string value, string[] order)
    {
        var index = Array.IndexOf(order, value);
        return index < 0 ? int.MaxValue : index;
    }

    private static (TimeZoneInfo TimeZone, string DisplayId) ResolveTimeZone(string? timeZoneId)
    {
        if (!string.IsNullOrWhiteSpace(timeZoneId))
        {
            try
            {
                var timeZone = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
                return (timeZone, timeZoneId);
            }
            catch (TimeZoneNotFoundException) { }
            catch (InvalidTimeZoneException) { }
        }
        return (TimeZoneInfo.Utc, "UTC");
    }

    private static DateTime ToLocalTime(DateTime utcValue, TimeZoneInfo timeZone) =>
        TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(utcValue, DateTimeKind.Utc), timeZone);

    private static void ApplySectionHeading(IXLRange range, XLColor blue)
    {
        range.Style.Fill.SetBackgroundColor(blue);
        range.Style.Font.SetBold().Font.SetFontColor(XLColor.White).Font.SetFontSize(9);
        range.Style.Alignment.SetVertical(XLAlignmentVerticalValues.Center);
    }

    private static void WriteBreakdown(IXLWorksheet sheet, int row, int column, string title,
        IReadOnlyCollection<(string Name, int Count)> items, XLColor blue, XLColor border)
    {
        var heading = sheet.Range(row, column, row, column + 1);
        heading.Merge().Value = title;
        ApplySectionHeading(heading, blue);
        var currentRow = row + 1;
        foreach (var item in items)
        {
            SetSafeText(sheet.Cell(currentRow, column), item.Name);
            sheet.Cell(currentRow, column + 1).SetValue(item.Count);
            sheet.Cell(currentRow, column + 1).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Right);
            var itemRange = sheet.Range(currentRow, column, currentRow, column + 1);
            itemRange.Style.Border.BottomBorder = XLBorderStyleValues.Hair;
            itemRange.Style.Border.BottomBorderColor = border;
            currentRow++;
        }
    }
}
