using ClosedXML.Excel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ResolveHub.Api.DTOs.Tickets;
using ResolveHub.Api.Services.Interfaces;

namespace ResolveHub.Api.Services.Implementations;

public sealed class AdminTicketReportService : IAdminTicketReportService
{
    private static readonly string[] Headers =
        ["Ticket Number", "Title", "Requester", "Category", "Priority", "Status", "Assigned Agent", "Created"];

    public byte[] CreatePdf(AdminTicketReportDto report, string generatedBy, DateTimeOffset generatedAt) =>
        Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(24);
            page.DefaultTextStyle(style => style.FontSize(8).FontColor(Colors.Grey.Darken3));
            page.Header().Column(column =>
            {
                column.Item().Text("ResolveHub").FontSize(18).Bold().FontColor("1769C2");
                column.Item().Text("Ticket Report").FontSize(14).SemiBold();
                column.Item().PaddingTop(5).Text($"Generated: {generatedAt:yyyy-MM-dd HH:mm 'UTC'}  |  Generated By: {generatedBy}")
                    .FontColor(Colors.Grey.Darken1);
            });
            page.Content().PaddingVertical(12).Column(column =>
            {
                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1.1f); columns.RelativeColumn(2.4f);
                        columns.RelativeColumn(1.5f); columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1); columns.RelativeColumn(1.1f);
                        columns.RelativeColumn(1.5f); columns.RelativeColumn(1.35f);
                    });
                    table.Header(header =>
                    {
                        foreach (var title in Headers)
                            header.Cell().Background("1769C2").Padding(5).Text(title).Bold().FontColor(Colors.White);
                    });
                    foreach (var ticket in report.Tickets)
                    {
                        AddPdfCell(table, ticket.TicketReferenceNumber);
                        AddPdfCell(table, ticket.Title);
                        AddPdfCell(table, ticket.RequesterName);
                        AddPdfCell(table, ticket.CategoryName);
                        AddPdfCell(table, ticket.PriorityName);
                        AddPdfCell(table, ticket.StatusName);
                        AddPdfCell(table, ticket.AssignedAgentName ?? "Unassigned");
                        AddPdfCell(table, ticket.CreatedDate.ToString("yyyy-MM-dd HH:mm"));
                    }
                });
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.Span("Page "); text.CurrentPageNumber(); text.Span(" of "); text.TotalPages();
            });
        })).GeneratePdf();

    public byte[] CreateExcel(AdminTicketReportDto report, string generatedBy, DateTimeOffset generatedAt)
    {
        using var workbook = new XLWorkbook();
        var summary = workbook.AddWorksheet("Summary");
        summary.Cell("A1").Value = "ResolveHub Ticket Report";
        summary.Cell("A1").Style.Font.SetBold().Font.SetFontSize(16).Font.SetFontColor(XLColor.FromHtml("#1769C2"));
        var details = new[]
        {
            ("Generated", generatedAt.ToString("yyyy-MM-dd HH:mm 'UTC'")),
            ("Generated By", generatedBy), ("Date Range", DateRange(report)),
            ("Search", report.Search), ("Status", report.Status),
            ("Category", report.Category), ("Priority", report.Priority),
            ("Total Matching Tickets", report.Tickets.Count.ToString())
        };
        for (var index = 0; index < details.Length; index++)
        {
            summary.Cell(index + 3, 1).Value = details[index].Item1;
            summary.Cell(index + 3, 1).Style.Font.SetBold();
            SetSafeText(summary.Cell(index + 3, 2), details[index].Item2);
        }
        summary.Columns(1, 2).AdjustToContents();

        var tickets = workbook.AddWorksheet("Tickets");
        for (var column = 0; column < Headers.Length; column++) tickets.Cell(1, column + 1).Value = Headers[column];
        var header = tickets.Range(1, 1, 1, Headers.Length);
        header.Style.Font.SetBold().Font.SetFontColor(XLColor.White);
        header.Style.Fill.SetBackgroundColor(XLColor.FromHtml("#1769C2"));
        for (var index = 0; index < report.Tickets.Count; index++)
        {
            var ticket = report.Tickets.ElementAt(index);
            var row = index + 2;
            SetSafeText(tickets.Cell(row, 1), ticket.TicketReferenceNumber);
            SetSafeText(tickets.Cell(row, 2), ticket.Title);
            SetSafeText(tickets.Cell(row, 3), ticket.RequesterName);
            SetSafeText(tickets.Cell(row, 4), ticket.CategoryName);
            SetSafeText(tickets.Cell(row, 5), ticket.PriorityName);
            SetSafeText(tickets.Cell(row, 6), ticket.StatusName);
            SetSafeText(tickets.Cell(row, 7), ticket.AssignedAgentName ?? "Unassigned");
            tickets.Cell(row, 8).Value = ticket.CreatedDate;
            tickets.Cell(row, 8).Style.DateFormat.Format = "yyyy-mm-dd hh:mm";
        }
        tickets.SheetView.FreezeRows(1);
        tickets.RangeUsed()?.SetAutoFilter();
        tickets.Columns().AdjustToContents(1, 40);
        tickets.Column(2).Width = Math.Min(50, Math.Max(20, tickets.Column(2).Width));
        tickets.Column(2).Style.Alignment.WrapText = true;
        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public string CreateFileName(AdminTicketReportDto report, string extension, DateTimeOffset generatedAt)
    {
        var range = report.FromUtc.HasValue && report.ToUtcExclusive.HasValue
            ? $"{report.FromUtc:yyyy-MM-dd}_to_{report.ToUtcExclusive.Value.AddTicks(-1):yyyy-MM-dd}"
            : $"All_Dates_{generatedAt:yyyy-MM-dd}";
        return $"ResolveHub_Ticket_Report_{range}.{extension}";
    }

    private static string DateRange(AdminTicketReportDto report) =>
        report.FromUtc.HasValue && report.ToUtcExclusive.HasValue
            ? $"{report.FromUtc:yyyy-MM-dd} to {report.ToUtcExclusive.Value.AddTicks(-1):yyyy-MM-dd}"
            : "All Dates";

    private static void AddPdfCell(TableDescriptor table, string value) =>
        table.Cell().BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4).Text(value);

    private static void SetSafeText(IXLCell cell, string value)
    {
        var safeValue = value.Length > 0 && "=+-@".Contains(value[0]) ? $"'{value}" : value;
        cell.Value = safeValue;
    }
}
